site_name: Warewulf
repo_url: https://github.com/SyntaxRules/warewulf3/
theme: readthedocs
docs_dir: 'docs'
pages:
    - 'Overview': 'index.md'
    - 'About': 'about.md'
    - 'Terminology': 'terminology.md'
    - 'Architecture': 'architecture.md'
    - 'Subprojects, Components & Plugins':
      - 'Warewulf Common': 'subprojects_components_plugins/common.md'
      - 'Data Store': 'subprojects_components_plugins/datastore.md'
      - 'Provisioning':
        - 'System/Node Provisioning': 'subprojects_components_plugins/provision.md'
        - 'File Provisioning': 'subprojects_components_plugins/provision-files.md'
        - 'Provisioned Runtime Scripts': 'subprojects_components_plugins/provision-scripts.md'
      - 'VNFS (Virtual Node File System) Management': 'subprojects_components_plugins/vnfs.md'
    - 'recipes':
      - 'Setup':
        - 'Installing': 'recipes/setup/installation.md'
        - 'Upgrading': 'recipes/setup/upgrading.md'
        - 'Initialization': 'recipes/setup/initialization.md'
        - 'Tab completion for wwsh': 'recipes/setup/readline.md'
      - 'Stateless Provisioning':
        - 'Red Hat and compatibles': 'recipes/provisioning/rhel.md'
        - 'Debian Linux': 'recipes/provisioning/debian.md'
      - 'General':
        - 'Adding Infiniband support to the VNFS': 'recipes/infiniband.md'
        - 'User management for provisioned nodes': 'recipes/users.md'
        - 'Provisioning nodes with multiple submasters': 'recipes/submaster-provisioning.md'
        - 'Stateful provisioning': 'recipes/stateful-provisioning.md'
        - 'Warewulf for PERCEUS Users': 'recipes/perceus-migration.md'
      - 'Development':
        - 'Warewulf Event Modules': 'event-modules.md'
        - 'Building with Mezzanine': 'mezzanine.md'
        - 'Contributing to Warewulf': 'contributing.md'
        - 'Building and installing from Source tarballs': 'recipes/setup/installation-by-source.md'
        - 'Building and installing from SCM repository (Subversion)': 'recipes/setup/installation-using-subversion.md'
